export const MuajiOptions = [
    {text: 1, value: 1},
    {text: 2, value: 2},
    {text: 3, value: 3},
    {text: 4, value: 4},
    {text: 5, value: 5},
    {text: 6, value: 6},
    {text: 7, value: 7},
    {text: 8, value: 8},
    {text: 9, value: 9},
    {text: 10, value: 10},
    {text: 11, value: 11},
    {text: 12, value: 12},
];
export const InstuticioniOptions =[
    {text:'UBT', value:'UBT'},
    {text:'UP', value:'UP'},
    {text:'Other', value:'Other'},
]
export const FakultetiOptions =[
    {text:'Menaxhment,Biznes dhe Ekonomi', value:'Menaxhment, Biznes dhe Ekonomi'},
    {text:'Shkenca Kompjuterike dhe Inxhinieri', value:'Shkenca Kompjuterike dhe Inxhinieri'},
    {text:'Menaxhment I Mekatronikes', value:'Menaxhment I Mekatronikes'},
    {text:'Sistemet e Informacionit', value:'Sisteme te Informacionit'},
    {text:'Arkitekture dhe Planifikim Hapesinor', value:'Arkitekturë dhe Planifikim Hapsinorë'},
    {text:'Inxhinieri Ndërtimore (Ndërtimtari) dhe Infrastrukturë', value:'Inxhinieri Ndërtimore (Ndërtimtari) dhe Infrastrukturë'},
    {text:'Shkenca Politike', value:'Shkenca Politike'},
    {text:'Juridik', value:'Juridik'},
    {text:'Media dhe Komunikim', value:'Media dhe Komunikim'},
    {text:'Inxhinieri e Energjisë', value:'Inxhinieri Energjisë'},
    {text:'Politika Publike dhe Menaxhimi', value:'Politika Publike dhe Menaxhimi'},
    {text:'Infermieri', value:'Infermieri'},
    {text:'Farmaci', value:'Farmaci'},
    {text:'Stomatologji', value:'Stomatologji'},
    {text:'Shkenca e Ushqimit dhe Bioteknologji', value:'Shkenca e Ushqimit dhe Bioteknologji'},
    {text:'Dizajn i Integruar', value:'Dizajn i Integruar'},
    {text:'Agrikulturë dhe Inxhinieri e Ambientit', value:'Agrikulturë dhe Inxhinieri e Ambientit'},
    {text:'Arti dhe Mediat Digjitale', value:'Arti dhe Mediat Digjitale'},
    {text:'Muzika Moderne, Prodhimi Digjital dhe Menaxhimi', value:'Muzika Moderne,Prodhimi Digjital dhe Menaxhimi'},
    {text:'Teknik i Anesteziologjisë', value:'Teknik i Anesteziologjisë'},
    {text:'Teknik i Radiologjisë', value:'Teknik i Radiologjisë'},
];
export const NiveliAkademikOptions =[
    {text:'Bsc', value:'Bsc'},
    {text:'MSc', value:'MSc'},
    {text:'Phd', value:'Phd'},
]
