export const Statusi = [
    { text: 'Published', value: 'published' },
    { text: 'In Press', value: 'inPress' },
    { text: 'Submitted', value: 'submitted' },
    { text: 'Unpublished', value: 'unpublished' },
]

export const LlojiPublikimit = [
    { text: 'Article', value: 'article' },
    { text: 'Book', value: 'book' },
    { text: 'Book Section', value: 'bookSection' },
    { text: 'Journal', value: 'journal' },
    { text: 'Monograph', value: 'monograph' },
    { text: 'Patent', value: 'patent' },
    { text: 'Conference', value: 'conference' },
    { text: 'Workshop Item', value: 'workshopItem' },
    { text: 'Teaching Resource', value: 'teachingResource' },
    { text: 'Other', value: 'other' },
]

export const Institucioni = [
    { text: 'UBT', value: 'ubt' },
    { text: 'UP', value: 'up' },
    { text: 'Other', value: 'other' },
]

export const Departamenti = [
    { text: 'Ju lutem zgjedhni departamentin', value: 'departamenti' },
    { text: 'Menaxhment, Biznes dhe Ekonomi', value: 'mbe' },
    { text: 'Shkenca Kompjuterike dhe Inxhinieri', value: 'shki' },
    { text: 'Menaxhim i Mekatronikës', value: 'mm' },
    { text: 'Sistemet e Informacionit', value: 'si' },
    { text: 'Arkitekturë dhe Planifikim Hapesinor', value: 'aph' },
    { text: 'Inxhinieri ndërtimore (Ndërtimtari) dhe Infrastrukturë', value: 'ini' },
    { text: 'Shkenca Politike', value: 'shp' },
    { text: 'Juridik', value: 'juridik' },
    { text: 'Media dhe Komunikim', value: 'mk' },
    { text: 'Inxhinieri e Energjisë', value: 'ie' },
    { text: 'Politika Publike dhe Menaxhimi', value: 'ppm' },
    { text: 'Infermieri', value: 'infermieri' },
    { text: 'Farmaci', value: 'farmaci' },
    { text: 'Stomatologji', value: 'stomatologji' },
    { text: 'Shkenca e Ushqimit dhe Bioteknologji', value: 'shub' },
    { text: 'Dizajn i Integruar', value: 'di' },
    { text: 'Agrikulturë dhe Inxhinieri e Ambientit', value: 'aia' },
    { text: 'Arti dhe Mediat Digjitale', value: 'amd' },
    { text: 'Muzika Moderne, Prodhimi Digjital dhe Menaxhimi', value: 'mmpdm' },
    { text: 'Teknik i Anesteziologjisë', value: 'ta' },
    { text: 'Teknik i Radiologjisë', value: 'tr' },
]

export const Kategorite = [
    { text: 'Zgjedheni kategorine', value: 'kategoria' },
    { text: "Accountancy, Financial Management", value: 'afm' },
    { text: 'Actuarial Science', value: 'as' },
    { text: 'Adult Education', value: 'ae' },
    { text: 'Aeronautical Engineering', value: 'aee' },
    { text: 'Agricultural Economics', value: 'age' },
    { text: 'Agricultural Sciences', value: 'ags' },
    { text: 'Agriculture', value: 'ag' },
    { text: 'Animal Husbandry', value: 'ah' },
    { text: 'Anthropology', value: 'ap' },
    { text: 'Archaeology', value: 'arc' },
    { text: 'Architecture', value: 'arch' },
    { text: 'Architecture, Urban and Regional Planning', value: 'aurp' },
    { text: 'Art and Design', value: 'ad' },
    { text: 'Artificial Intelligence', value: 'ai' },
    { text: 'Astronomy, Astrophysics', value: 'aa' },
    { text: 'Automatic gepesites', value: 'ag' },
    { text: 'Biochemistry', value: 'bioch' },
    { text: 'Biology', value: 'bio' },
    { text: 'Biometrics', value: 'biom' },
    { text: 'Biophysics', value: 'biop' },
    { text: 'Botany', value: 'bot' },
    { text: 'Business Organisation', value: 'bo' },
    { text: 'Business Studies with languages', value: 'bsl' },
    { text: 'Business Studies with technology', value: 'bst' },
    { text: 'Business Studies, Management Science', value: 'bsms' },
    { text: 'Chemical Engineering', value: 'che' },
    { text: 'Chemistry', value: 'ch' },
    { text: 'Civil Engineering', value: 'ce' },
    { text: 'Civil Law', value: 'cl' },
    { text: 'Classical Philology', value: 'cp' },
    { text: 'Commerce and tourism', value: 'ct' },
    { text: 'Communication and Information Sciences', value: 'cis' },
    { text: 'Comparative Law, Law with Languages', value: 'clll' },
    { text: 'Computer Science', value: 'cs' },
    { text: 'Constitutional Public Law', value: 'cpl' },
    { text: 'Criminal Law, Criminology', value: 'clc' },
    { text: 'Cultivation,growing of vegetables,medical and aromatic plants', value: 'agvmap' },
    { text: 'Culture, sport', value: 'cspo' },
    { text: 'Dentistry', value: 'dent' },
    { text: 'Desicion making', value: 'dm' },
    { text: 'Design (Graphic Design, Industrial Design, Fashion, Textile)', value: 'design' },
    { text: 'Development Studies', value: 'ds' },
    { text: 'Documentation, Archiving', value: 'da' },
    { text: 'Ecology', value: 'eco' },
    { text: 'Economic history', value: 'eh' },
    { text: 'Economic policy', value: 'ep' },
    { text: 'Economics', value: 'econo' },
    { text: 'Education', value: 'edu' },
    { text: 'Education, Teacher Training', value: 'ett' },
    { text: 'Educational Psychology', value: 'edup' },
    { text: 'Educational Science, Comparative Education', value: 'esce' },
    { text: 'Electrical Engineering', value: 'ee' },
    { text: 'Electronic Engineering, Telecommunications', value: 'eet' },
    { text: 'Energy economy', value: 'eeco' },
    { text: 'Engineering, Technology', value: 'et' },
    { text: 'Enviromental economics', value: 'eecon' },
    { text: 'Environmental Sciences, Ecology', value: 'ese' },
    { text: 'Ethnography, anthropology', value: 'eanth' },
    { text: 'European Community/EU Law', value: 'eceul' },
    { text: 'Finance', value: 'fin' },
    { text: 'Fine Art (Painting, Sculpture, Printmaking)', value: 'fa' },
    { text: 'Fisheries', value: 'fish' },
    { text: 'Food and biotechnology', value: 'fbio' },
    { text: 'Food economy', value: 'fe' },
    { text: 'Food safety and equality', value: 'fse' },
    { text: 'Food science', value: 'fs' },
    { text: 'Food Science and Technology', value: 'fst' },
    { text: 'Forestry', value: 'fore' },
    { text: 'Futures Research', value: 'fr' },
    { text: 'General and comparative literature', value: 'gcl' },
    { text: 'General Statistics', value: 'gs' },
    { text: 'Genetics', value: 'gene' },
    { text: 'Geodesy, Cartography, Remote Sensing', value: 'gcrs' },
    { text: 'Geography', value: 'geo' },
    { text: 'Geography, Geology', value: 'gg' },
    { text: 'Geology', value: 'geology' },
    { text: 'History', value: 'history' },
    { text: 'History of Art', value: 'ha' },
    { text: 'Home Economics, Nutrition', value: 'hen' },
    { text: 'Horticulture', value: 'horti' },
    { text: 'Human Resources Management', value: 'hrm' },
    { text: 'Humanities', value: 'human' },
    { text: 'Industrial Relations and Personnel Management', value: 'irpm' },
    { text: 'Industry', value: 'industry' },
    { text: 'Informatics, Computer Science', value: 'ics' },
    { text: 'Information economy', value: 'ieco' },
    { text: 'Interior Design', value: 'id' },
    { text: 'International economics', value: 'ie' },
    { text: 'International Law', value: 'il' },
    { text: 'International relations', value: 'ir' },
    { text: 'International Relations, European Studies, Area Studies', value: 'iresas' },
    { text: 'Journalism', value: 'journalism' },
    { text: 'Knowledge economy,innovation', value: 'kei' },
    { text: 'Labour economics', value: 'le' },
    { text: 'Landscape Architecture', value: 'la' },
    { text: 'Languages and Philological Sciences', value: 'lps' },
    { text: 'Law', value: 'law' },
    { text: 'Leisure Studies', value: 'ls' },
    { text: 'Less Widely Taught Languages', value: 'lwtl' },
    { text: 'Library Science', value: 'lsci' },
    { text: 'Linguistics', value: 'ling' },
    { text: 'Manufacturing Sciences (including CAD, CAM, CAE)', value: 'manus' },
    { text: 'Marketing and Sales Management', value: 'msm' },
    { text: 'Materials Science', value: 'ms' },
    { text: 'Mathematics', value: 'math' },
    { text: 'Mathematics, Informatics', value: 'mathi' },
    { text: 'Mechanical Engineering', value: 'me' },
    { text: 'Medical Sciences', value: 'meds' },
    { text: 'Medical Technology', value: 'medt' },
    { text: 'Medicine', value: 'medicine' },
    { text: 'Meteorology', value: 'meteo' },
    { text: 'Microbiology, Biotechnology', value: 'microbio' },
    { text: 'Modern EC Languages', value: 'mecl' },
    { text: 'Museum Studies, Conservation', value: 'msc' },
    { text: 'Music and Musicology', value: 'mm' },
    { text: 'Natural Sciences', value: 'ns' },
    { text: 'Nautical Science, Navigation', value: 'nsn' },
    { text: 'Non-EC Languages', value: 'necl' },
    { text: 'Nuclear and High Energy Physics', value: 'nhep' },
    { text: 'Nursing, Midwifery, Physiotherapy', value: 'nmp' },
    { text: 'Oceanography', value: 'ocean' },
    //  "12Other Areas of Study
    //  "130"Others - Geography, Geology
    //  "131"Others - Languages and Philological Sciences
    //  "132"Others - Law
    //  "133"Others in Other Areas of Study
    { text: 'Performing Arts', value: 'pa' },
    { text: 'Pharmacy', value: 'pharmacy' },
    { text: 'Philosophy', value: 'philosophy' },
    { text: 'Photography, Cinematography', value: 'photocinema' },
    { text: 'Physical Education, Sport Science', value: 'pess' },
    { text: 'Physics', value: 'physics' },
    { text: 'Political Science', value: 'ps' },
    { text: 'Primary Education', value: 'pe' },
    { text: 'Psychiatry and Clinical Psychology', value: 'pcp' },
    { text: 'Psychology and Behavioural Sciences', value: 'pbs' },
    { text: 'Public Administration', value: 'padmin' },
    { text: 'Public Health', value: 'ph' },
    { text: 'Public Relations, Publicity, Advertising', value: 'prpa' },
    { text: 'RadioTV Broadcasting', value: 'radiotv' },
    { text: 'Regional Planning', value: 'rp' },
    { text: 'Secondary Education', value: 'se' },
    { text: 'Secretarial Studies', value: 'sstudies' },
    { text: 'Social Sciences', value: 'socials' },
    { text: 'Social Work', value: 'sw' },
    { text: 'Sociology', value: 'sociology' },
    { text: 'Soil and Water Sciences', value: 'sws' },
    { text: 'Special Education', value: 'sedu' },
    { text: 'Statistics', value: 'statistics' },
    { text: 'Teacher Training', value: 'tt' },
    { text: 'Theology', value: 'theology' },
    { text: 'Tourism, Catering, Hotel Management', value: 'tchm' },
    { text: 'Translation, Interpretation', value: 'ti' },
    { text: 'Transport and Traffic Studies', value: 'tts' },
    { text: 'TropicalSubtropical Agriculture', value: 'tsa' },
    { text: 'Urban Planning', value: 'up' },
    { text: 'Veterinary Medicine', value: 'vm' },
    { text: 'Vocational and Technical Education', value: 'vte' }
]