export const Statusi = [
    { text: 'Published', value: 'Published' },
    { text: 'In Press', value: 'In Press' },
    { text: 'Submitted', value: 'Submitted' },
    { text: 'Unpublished', value: 'Unpublished' },
]

export const LlojiPublikimit = [
    { text: 'Article', value: 'Article' },
    { text: 'Book', value: 'Book' },
    { text: 'Book Section', value: 'Book Section' },
    { text: 'Journal', value: 'Journal' },
    { text: 'Monograph', value: 'Monograph' },
    { text: 'Patent', value: 'Patent' },
    { text: 'Conference', value: 'Conference' },
    { text: 'Workshop Item', value: 'Workshop Item' },
    { text: 'Teaching Resource', value: 'Teaching Resource' },
    { text: 'Other', value: 'Other' },
]

export const Institucioni = [
    { text: 'UBT', value: 'UBT' },
    { text: 'UP', value: 'UP' },
    { text: 'Other', value: 'Other' },
]

export const Departamenti = [
    // { text: 'Ju lutem zgjedhni departamentin', value: 'departamenti' },
    { text: 'Menaxhment, Biznes dhe Ekonomi', value: 'Menaxhment, Biznes dhe Ekonomi' },
    { text: 'Shkenca Kompjuterike dhe Inxhinieri', value: 'Shkenca Kompjuterike dhe Inxhinieri' },
    { text: 'Menaxhim i Mekatronikës', value: 'Menaxhim i Mekatronikës' },
    { text: 'Sistemet e Informacionit', value: 'Sistemet e Informacionit' },
    { text: 'Arkitekturë dhe Planifikim Hapesinor', value: 'Arkitekturë dhe Planifikim Hapesinor' },
    { text: 'Inxhinieri ndërtimore (Ndërtimtari) dhe Infrastrukturë', value: 'Inxhinieri ndërtimore (Ndërtimtari) dhe Infrastrukturë' },
    { text: 'Shkenca Politike', value: 'Shkenca Politike' },
    { text: 'Juridik', value: 'Juridik' },
    { text: 'Media dhe Komunikim', value: 'Media dhe Komunikim' },
    { text: 'Inxhinieri e Energjisë', value: 'Inxhinieri e Energjisë' },
    { text: 'Politika Publike dhe Menaxhimi', value: 'Politika Publike dhe Menaxhimi' },
    { text: 'Infermieri', value: 'Infermieri' },
    { text: 'Farmaci', value: 'Farmaci' },
    { text: 'Stomatologji', value: 'Stomatologji' },
    { text: 'Shkenca e Ushqimit dhe Bioteknologji', value: 'Shkenca e Ushqimit dhe Bioteknologji' },
    { text: 'Dizajn i Integruar', value: 'Dizajn i Integruar' },
    { text: 'Agrikulturë dhe Inxhinieri e Ambientit', value: 'Agrikulturë dhe Inxhinieri e Ambientit' },
    { text: 'Arti dhe Mediat Digjitale', value: 'Arti dhe Mediat Digjitale' },
    { text: 'Muzika Moderne, Prodhimi Digjital dhe Menaxhimi', value: 'Muzika Moderne, Prodhimi Digjital dhe Menaxhimi' },
    { text: 'Teknik i Anesteziologjisë', value: 'Teknik i Anesteziologjisë' },
    { text: 'Teknik i Radiologjisë', value: 'Teknik i Radiologjisë' },
]

export const Kategorite = [
    // { text: 'Zgjedheni kategorine', value: 'kategoria' },
    { text: "Accountancy, Financial Management", value: 'Accountancy, Financial Management' },
    { text: 'Actuarial Science', value: 'Actuarial Science' },
    { text: 'Adult Education', value: 'Adult Education' },
    { text: 'Aeronautical Engineering', value: 'Aeronautical Engineering' },
    { text: 'Agricultural Economics', value: 'Agricultural Economics' },
    { text: 'Agricultural Sciences', value: 'Agricultural Sciences' },
    { text: 'Agriculture', value: 'Agriculture' },
    { text: 'Animal Husbandry', value: 'Animal Husbandry' },
    { text: 'Anthropology', value: 'Anthropology' },
    { text: 'Archaeology', value: 'Archaeology' },
    { text: 'Architecture', value: 'Architecture' },
    { text: 'Architecture, Urban and Regional Planning', value: 'Architecture, Urban and Regional Planning' },
    { text: 'Art and Design', value: 'Art and Design' },
    { text: 'Artificial Intelligence', value: 'Artificial Intelligence' },
    { text: 'Astronomy, Astrophysics', value: 'Astronomy, Astrophysics' },
    { text: 'Automatic gepesites', value: 'Automatic gepesites' },
    { text: 'Biochemistry', value: 'Biochemistry' },
    { text: 'Biology', value: 'Biology' },
    { text: 'Biometrics', value: 'Biometrics' },
    { text: 'Biophysics', value: 'Biophysics' },
    { text: 'Botany', value: 'Botany' },
    { text: 'Business Organisation', value: 'Business Organisation' },
    { text: 'Business Studies with languages', value: 'Business Studies with languages' },
    { text: 'Business Studies with technology', value: 'Business Studies with technology' },
    { text: 'Business Studies, Management Science', value: 'Business Studies, Management Science' },
    { text: 'Chemical Engineering', value: 'Chemical Engineering' },
    { text: 'Chemistry', value: 'Chemistry' },
    { text: 'Civil Engineering', value: 'Civil Engineering' },
    { text: 'Civil Law', value: 'Civil Law' },
    { text: 'Classical Philology', value: 'Classical Philology' },
    { text: 'Commerce and tourism', value: 'Commerce and tourism' },
    { text: 'Communication and Information Sciences', value: 'Communication and Information Sciences' },
    { text: 'Comparative Law, Law with Languages', value: 'Comparative Law, Law with Languages' },
    { text: 'Computer Science', value: 'Computer Science' },
    { text: 'Constitutional Public Law', value: 'Constitutional Public Law' },
    { text: 'Criminal Law, Criminology', value: 'Criminal Law, Criminology' },
    { text: 'Cultivation,growing of vegetables,medical and aromatic plants', value: 'Cultivation,growing of vegetables,medical and aromatic plants' },
    { text: 'Culture, sport', value: 'Culture, sport' },
    { text: 'Dentistry', value: 'Dentistry' },
    { text: 'Desicion making', value: 'Desicion making' },
    { text: 'Design (Graphic Design, Industrial Design, Fashion, Textile)', value: 'Design (Graphic Design, Industrial Design, Fashion, Textile)' },
    { text: 'Development Studies', value: 'Development Studies' },
    { text: 'Documentation, Archiving', value: 'Documentation, Archiving' },
    { text: 'Ecology', value: 'Ecology' },
    { text: 'Economic history', value: 'Economic history' },
    { text: 'Economic policy', value: 'Economic policy' },
    { text: 'Economics', value: 'Economics' },
    { text: 'Education', value: 'Education' },
    { text: 'Education, Teacher Training', value: 'Education, Teacher Training' },
    { text: 'Educational Psychology', value: 'Educational Psychology' },
    { text: 'Educational Science, Comparative Education', value: 'Educational Science, Comparative Education' },
    { text: 'Electrical Engineering', value: 'Electrical Engineering' },
    { text: 'Electronic Engineering, Telecommunications', value: 'Electronic Engineering, Telecommunications' },
    { text: 'Energy economy', value: 'Energy economy' },
    { text: 'Engineering, Technology', value: 'Engineering, Technology' },
    { text: 'Enviromental economics', value: 'Enviromental economics' },
    { text: 'Environmental Sciences, Ecology', value: 'Environmental Sciences, Ecology' },
    { text: 'Ethnography, anthropology', value: 'Ethnography, anthropology' },
    { text: 'European Community/EU Law', value: 'European Community/EU Law' },
    { text: 'Finance', value: 'Finance' },
    { text: 'Fine Art (Painting, Sculpture, Printmaking)', value: 'Fine Art (Painting, Sculpture, Printmaking)' },
    { text: 'Fisheries', value: 'Fisheries' },
    { text: 'Food and biotechnology', value: 'Food and biotechnology' },
    { text: 'Food economy', value: 'Food economy' },
    { text: 'Food safety and equality', value: 'Food safety and equality' },
    { text: 'Food science', value: 'Food science' },
    { text: 'Food Science and Technology', value: 'Food Science and Technology' },
    { text: 'Forestry', value: 'Forestry' },
    { text: 'Futures Research', value: 'Futures Research' },
    { text: 'General and comparative literature', value: 'General and comparative literature' },
    { text: 'General Statistics', value: 'General Statistics' },
    { text: 'Genetics', value: 'Genetics' },
    { text: 'Geodesy, Cartography, Remote Sensing', value: 'Geodesy, Cartography, Remote Sensing' },
    { text: 'Geography', value: 'Geography' },
    { text: 'Geography, Geology', value: 'Geography, Geology' },
    { text: 'Geology', value: 'Geology' },
    { text: 'History', value: 'History' },
    { text: 'History of Art', value: 'History of Art' },
    { text: 'Home Economics, Nutrition', value: 'Home Economics, Nutrition' },
    { text: 'Horticulture', value: 'Horticulture' },
    { text: 'Human Resources Management', value: 'Human Resources Management' },
    { text: 'Humanities', value: 'Humanities' },
    { text: 'Industrial Relations and Personnel Management', value: 'Industrial Relations and Personnel Management' },
    { text: 'Industry', value: 'Industry' },
    { text: 'Informatics, Computer Science', value: 'Informatics, Computer Science' },
    { text: 'Information economy', value: 'Information economy' },
    { text: 'Interior Design', value: 'Interior Design' },
    { text: 'International economics', value: 'International economics' },
    { text: 'International Law', value: 'International Law' },
    { text: 'International relations', value: 'International relations' },
    { text: 'International Relations, European Studies, Area Studies', value: 'International Relations, European Studies, Area Studies' },
    { text: 'Journalism', value: 'Journalism' },
    { text: 'Knowledge economy,innovation', value: 'Knowledge economy,innovation' },
    { text: 'Labour economics', value: 'Labour economics' },
    { text: 'Landscape Architecture', value: 'Landscape Architecture' },
    { text: 'Languages and Philological Sciences', value: 'Languages and Philological Sciences' },
    { text: 'Law', value: 'Law' },
    { text: 'Leisure Studies', value: 'Leisure Studies' },
    { text: 'Less Widely Taught Languages', value: 'Less Widely Taught Languages' },
    { text: 'Library Science', value: 'Library Science' },
    { text: 'Linguistics', value: 'Linguistics' },
    { text: 'Manufacturing Sciences (including CAD, CAM, CAE)', value: 'Manufacturing Sciences (including CAD, CAM, CAE)' },
    { text: 'Marketing and Sales Management', value: 'Marketing and Sales Management' },
    { text: 'Materials Science', value: 'Materials Science' },
    { text: 'Mathematics', value: 'Mathematics' },
    { text: 'Mathematics, Informatics', value: 'Mathematics, Informatics' },
    { text: 'Mechanical Engineering', value: 'Mechanical Engineering' },
    { text: 'Medical Sciences', value: 'Medical Sciences' },
    { text: 'Medical Technology', value: 'Medical Technology' },
    { text: 'Medicine', value: 'Medicine' },
    { text: 'Meteorology', value: 'Meteorology' },
    { text: 'Microbiology, Biotechnology', value: 'Microbiology, Biotechnology' },
    { text: 'Modern EC Languages', value: 'Modern EC Languages' },
    { text: 'Museum Studies, Conservation', value: 'Museum Studies, Conservation' },
    { text: 'Music and Musicology', value: 'Music and Musicology' },
    { text: 'Natural Sciences', value: 'Natural Sciences' },
    { text: 'Nautical Science, Navigation', value: 'Nautical Science, Navigation' },
    { text: 'Non-EC Languages', value: 'Non-EC Languages' },
    { text: 'Nuclear and High Energy Physics', value: 'Nuclear and High Energy Physics' },
    { text: 'Nursing, Midwifery, Physiotherapy', value: 'Nursing, Midwifery, Physiotherapy' },
    { text: 'Oceanography', value: 'Oceanography' },
    //  "12Other Areas of Study
    //  "130"Others - Geography, Geology
    //  "131"Others - Languages and Philological Sciences
    //  "132"Others - Law
    //  "133"Others in Other Areas of Study
    { text: 'Performing Arts', value: 'Performing Arts' },
    { text: 'Pharmacy', value: 'Pharmacy' },
    { text: 'Philosophy', value: 'Philosophy' },
    { text: 'Photography, Cinematography', value: 'Photography, Cinematography' },
    { text: 'Physical Education, Sport Science', value: 'Physical Education, Sport Science' },
    { text: 'Physics', value: 'Physics' },
    { text: 'Political Science', value: 'Political Science' },
    { text: 'Primary Education', value: 'Primary Education' },
    { text: 'Psychiatry and Clinical Psychology', value: 'Psychiatry and Clinical Psychology' },
    { text: 'Psychology and Behavioural Sciences', value: 'Psychology and Behavioural Sciences' },
    { text: 'Public Administration', value: 'Public Administration' },
    { text: 'Public Health', value: 'Public Health' },
    { text: 'Public Relations, Publicity, Advertising', value: 'Public Relations, Publicity, Advertising' },
    { text: 'RadioTV Broadcasting', value: 'RadioTV Broadcasting' },
    { text: 'Regional Planning', value: 'Regional Planning' },
    { text: 'Secondary Education', value: 'Secondary Education' },
    { text: 'Secretarial Studies', value: 'Secretarial Studies' },
    { text: 'Social Sciences', value: 'Social Sciences' },
    { text: 'Social Work', value: 'Social Work' },
    { text: 'Sociology', value: 'Sociology' },
    { text: 'Soil and Water Sciences', value: 'Soil and Water Sciences' },
    { text: 'Special Education', value: 'Special Education' },
    { text: 'Statistics', value: 'Statistics' },
    { text: 'Teacher Training', value: 'Teacher Training' },
    { text: 'Theology', value: 'Theology' },
    { text: 'Tourism, Catering, Hotel Management', value: 'Tourism, Catering, Hotel Management' },
    { text: 'Translation, Interpretation', value: 'Translation, Interpretation' },
    { text: 'Transport and Traffic Studies', value: 'Transport and Traffic Studies' },
    { text: 'TropicalSubtropical Agriculture', value: 'TropicalSubtropical Agriculture' },
    { text: 'Urban Planning', value: 'Urban Planning' },
    { text: 'Veterinary Medicine', value: 'Veterinary Medicine' },
    { text: 'Vocational and Technical Education', value: 'Vocational and Technical Education' }
]